import { AttireGuide, EventDef, EventKey } from "./types";

export const EVENTS: EventDef[] = [
  {
    key: "kirtan",
    name: "Kirtan",
    dateLabel: "Sat 5 Dec",
    dateFull: "05 December, Saturday 2026",
    time: "6:00 PM – 9:00 PM",
    venue: "Iskon Temple",
    place: "Chowpatty, Mumbai",
    card: "/cards/kirtan.jpg",
    thumb: "/cards/thumbs/kirtan.jpg",
    accent: "#12545B",
    accentDark: "#0A363B",
    dress: "",
  },
  {
    key: "bridalShower",
    name: "Bridal Shower",
    dateLabel: "Tue 8 Dec",
    dateFull: "08 December, Tuesday 2026",
    time: "5:30 PM – 7:30 PM",
    venue: "Eva Room",
    place: "Soho Club Juhu, Mumbai",
    card: "/cards/bridal-shower.jpg",
    thumb: "/cards/thumbs/bridal-shower.jpg",
    accent: "#6E4E96",
    accentDark: "#4A3168",
    dress: "Summer florals",
  },
  {
    key: "mehendi",
    name: "Mehendi",
    dateLabel: "Wed 9 Dec",
    dateFull: "09 December, Wednesday 2026",
    time: "6:00 PM onwards",
    venue: "Rooftop, Pool Side",
    place: "Karl Residency, Andheri, Mumbai",
    card: "/cards/mehendi.jpg",
    thumb: "/cards/thumbs/mehendi.jpg",
    accent: "#4E5C2E",
    accentDark: "#333D1C",
    dress: "Vibrant & Artistic",
  },
  {
    key: "soiree",
    name: "Musical Soiree",
    dateLabel: "Fri 11 Dec",
    dateFull: "11 December, Friday 2026",
    time: "6:00 PM – 10:00 PM",
    venue: "Amphitheater",
    place: "Ikshana Resort, Lonavala",
    card: "/cards/soiree.jpg",
    thumb: "/cards/thumbs/soiree.jpg",
    accent: "#6B4426",
    accentDark: "#3F2716",
    dress: "Western Cocktail",
  },
  {
    key: "djNight",
    name: "The Inner Circle DJ Night",
    dateLabel: "Fri 11 Dec",
    dateFull: "11 December, Friday 2026",
    time: "10:00 PM onwards",
    venue: "Aasthan 1",
    place: "Ikshana Resort, Lonavala",
    card: "/cards/dj-night.jpg",
    thumb: "/cards/thumbs/dj-night.jpg",
    accent: "#443078",
    accentDark: "#281B4C",
    dress: "",
  },
  {
    key: "haldi",
    name: "Haldi",
    dateLabel: "Sat 12 Dec",
    dateFull: "12 December, Saturday 2026",
    time: "10:00 AM – 1:00 PM",
    venue: "Pool Side",
    place: "Ikshana Resort, Lonavala",
    card: "/cards/haldi.jpg",
    thumb: "/cards/thumbs/haldi.jpg",
    accent: "#C08A2E",
    accentDark: "#8A5D14",
    dress: "Sunny & Traditional",
  },
  {
    key: "pheras",
    name: "Baraat, Varmala & Phera",
    dateLabel: "Sat 12 Dec",
    dateFull: "12 December, Saturday 2026",
    time: "Baraat 3:00 PM at the Lobby · Varmala & Phera 4:30 PM onwards at Vaayuvan Terrace",
    timeShort: "Baraat 3:00 PM · Phera 4:30 PM",
    venue: "Lobby & Vaayuvan Terrace",
    place: "Ikshana Resort, Lonavala",
    card: "/cards/pheras.jpg",
    cards: ["/cards/pheras-1.jpg", "/cards/pheras.jpg"],
    thumb: "/cards/thumbs/pheras.jpg",
    accent: "#A02234",
    accentDark: "#6B1220",
    dress: "Heavy Indian Traditional",
  },
];

export const EVENT_MAP: Record<EventKey, EventDef> = EVENTS.reduce(
  (acc, e) => ({ ...acc, [e.key]: e }),
  {} as Record<EventKey, EventDef>
);

export const WEDDING_DATE_ISO = "2026-12-12T15:00:00+05:30";

export const ATTIRE: Partial<Record<EventKey, AttireGuide>> = {
  mehendi: {
    mood: "Vibrant and artistic",
    avoid: "Please do not wear red.",
    wear: "Kurta with churidar, sharara, anarkali, printed lehenga, or a light jacket over trousers.",
    colours: [
      { name: "Sage Green", hex: "#A8BE94" },
      { name: "Emerald Green", hex: "#2E9E6B" },
      { name: "Olive Green", hex: "#6E7A1E" },
      { name: "Khaki", hex: "#C3BE9A" },
      { name: "Tiffany Blue", hex: "#2FA8A5" },
      { name: "Ice Blue", hex: "#A5F2F3" },
      { name: "Denim", hex: "#1F4CA8" },
      { name: "Lilac to Violet", hex: "#8E4FD0" },
    ],
  },
  soiree: {
    mood: "Western cocktail",
    avoid: "Please do not wear magenta or red.",
    wear: "Cocktail dress, gown, jumpsuit, or a suit and blazer with trousers.",
    colours: [
      { name: "Blush to Peach", hex: "#F5CBBB" },
      { name: "Emerald Green", hex: "#2E9E6B" },
      { name: "Champagne Gold", hex: "#E8DCA8" },
      { name: "Silver", hex: "#B8B8B8" },
      { name: "Navy Blue", hex: "#14235C" },
      { name: "Charcoal to Black", hex: "#262E33" },
      { name: "White", hex: "#FFFFFF" },
    ],
  },
  haldi: {
    mood: "Sunny and traditional",
    avoid: "Please do not wear pink.",
    wear: "Cotton kurta, saree, easy salwar, or a kurta with a light dupatta. Something you will not mind turmeric on.",
    colours: [
      { name: "Turmeric to Mustard", hex: "#D99A08" },
      { name: "Lemon", hex: "#E9DF4A" },
      { name: "Marigold to Tangerine", hex: "#F08321" },
      { name: "Caramel", hex: "#A9711F" },
      { name: "Sand", hex: "#D9CDB0" },
      { name: "Mint Green", hex: "#A9E5B8" },
    ],
  },
  pheras: {
    mood: "Heavy Indian traditional",
    avoid: "Please do not wear purple or violet.",
    wear: "Sherwani, bandhgala, heavy saree, lehenga, or a formal suit.",
    colours: [
      { name: "Rust to Terracotta", hex: "#BE5232" },
      { name: "Apricot", hex: "#F3C79D" },
      { name: "Cherry Blossom", hex: "#FFB7C5" },
      { name: "Baby Blue", hex: "#A9CFE8" },
      { name: "Navy Blue", hex: "#14235C" },
      { name: "Slate to Charcoal", hex: "#5A6670" },
      { name: "Ivory", hex: "#F5EFE0" },
    ],
  },
};

export const INVITED_COLUMN_BY_KEY: Record<EventKey, string> = {
  kirtan: "invited_kirtan",
  bridalShower: "invited_bridal_shower",
  mehendi: "invited_mehendi",
  soiree: "invited_soiree",
  djNight: "invited_dj_night",
  haldi: "invited_haldi",
  pheras: "invited_pheras",
};
